### ISSUE TITLE
RV Plot Period Rounding

### ISSUE THREAD

**Issue by bjfultn** [California-Planet-Search/radvel#110]
Period values seem to be rounded to the nearest day when fixed in the fitting.

**Comment by smmills** [comment]
This can be reproduced by doing the following (at least on my machine):

In the HD164922.py file in the example_planets directory, add on line 53
    params['per1'].vary = False
and then run:
$ radvel fit -s HD164922.py
$ radvel mcmc -s HD164922.py
$ radvel plot -t rv -s HD164922.py

**Comment by bjfultn** [comment]
This is fixed and staged for release in v1.0.4. See commit 1666f576bd
