### ISSUE TITLE
GP multipanel plotting

### ISSUE THREAD

**Issue by sblunt** [California-Planet-Search/radvel#121]
How should we handle plotting best-fit solutions using multiple GP likelihoods? Currently, plotting a separate GP mean function for each likelihood can lead to confusing-looking plots. Assignees plan to meet at some point to discuss this issue.

**Comment by bjfultn** [comment]
I believe we have a plan for this now. @sblunt is working on the implementation

**Comment by sblunt** [comment]
Addressed in Version 1.1.10.
