### ISSUE TITLE
Minor Jitter Error in SyntheticData.ipynb

### ISSUE THREAD

**Issue by smmills** [California-Planet-Search/radvel#123]
In the SyntheticData.ipynb example notebook when you construct the dataset, I think a jitter is not added in (jitter=0). 

However, the prior on the jitter is confusingly not centered on zero:
```
errvel=0.3
post.priors += [radvel.prior.Gaussian( 'jit', errvel, 0.1)]
```
And the vertical line for the "true value" is incorrectly located at errvel=0.3:
`like_syn.params['jit'] = radvel.Parameter(value=errvel)`

In the notebook, when uncertainties are added they are added equal to the formal uncertainties on the data points:
`syn_rv = rv_mod(t) + randn(t.size)*errvel`

To add a jitter equal to errvel would require:
```
jitvel = 0.3
like_syn.params['jit'] = radvel.Parameter(value=jitvel)
syn_rv = rv_mod(t) + randn(t.size)*np.sqrt(errvel^2 + jitvel^2)
```
but keeping
`like_syn = radvel.likelihood.RVLikelihood(rv_mod,t,syn_rv,zeros(t.size)+errvel)`

**Comment by bjfultn** [comment]
Thanks for catching this @smmills! This bug is fixed in commit e23d30.
