### ISSUE TITLE
basis cleanup

### ISSUE THREAD

**Issue by sealauren** [California-Planet-Search/radvel#127]
It looks like "logper..." is not currently available as a fitting basis.  Error output:

Performing max-likelihood fitting for ******
logper tc secosw sesinw logk not valid basis
Available bases:
per tp e w k
per tc secosw sesinw logk
per tc secosw sesinw k
per tc e w k

Can we make sure fitting and mcmc work for the following bases:
logper tc secosw sesinw logk
logper tc e w logk

**Comment by bjfultn** [comment]
I just verified that this works in versions of radvel>=1.0.3. Please update your installation and try again.
