### ISSUE TITLE
Cython version conflicts

### ISSUE THREAD

**Issue by bjfultn** [California-Planet-Search/radvel#134]
Identify which version of cython is actually needed (0.27.3 definitely works) and update the requirements.txt file appropriately. The current minimum requirement of >=0.22 doesn't seem to work.

**Comment by bjfultn** [comment]
What OS did you test this on?

**Comment by sblunt** [comment]
Mac. Right I forgot the problem was with a different OS.

**Comment by bjfultn** [comment]
Can you run this test on cadence also?

**Comment by sblunt** [comment]
Yup, no problem.

**Comment by sblunt** [comment]
Strangely, the first time I ran this test on cadence, cython versions 0.22 and 0.22.1 failed to build radvel properly in python 3.6 only. But after I had built radvel using a later version of cython, all the tests passed and I couldn't reproduce the error, even if I deleted the original conda environment and tried version 0.22 in a completely new conda environment. I think we probably need to run these tests individually for each cython version/python version in actual virtual environments. What do you think? Regardless, we should stop allowing cython versions 0.22 and 0.22.1.

**Comment by bjfultn** [comment]
Hmm, thats pretty strange. However, if we can fix this by simply requiring cython>=0.23 then I'm satisfied. Do you think that will work?

**Comment by sblunt** [comment]
Yeah, I'm satisfied with that. I think the non-failure may have something to do with wheel-building... regardless, I'm happy with that fix.

**Comment by bjfultn** [comment]
Requiring cython>=0.23 in commit c8e199af772ca6e014cda983b6d4c17474203320
