### ISSUE TITLE
C Kepler solver not building on Ubuntu 17.0.4

### ISSUE THREAD

**Issue by bjfultn** [California-Planet-Search/radvel#135]
The C code doesn't seem to build when on Ubuntu 17.0.4. This was discovered when working with Stephen Kane on 2/2/2018.

**Comment by bjfultn** [comment]
@cytherean could you verify you were running on 17.0.4? This seems like an uncommon distribution of Ubuntu. 17.10 seems to be the normal version of 17.

**Comment by cytherean** [comment]
It's Ubuntu 17.04 (zesty). 17.10 is the latest upgrade to the Ubuntu 17 distribution.

**Comment by bjfultn** [comment]
Ok, roger that. I will try to setup a virtual environment in 17.04 to see if I can reproduce the issue.

**Comment by bjfultn** [comment]
I had trouble setting up an Ubuntu 17.0.4 virtual environment because `apt-get` commands don't work. Instead I set up Ubuntu 17.10 and I could not reproduce this issue. 

@cytherean lets try to build the code directly from the source to see if that produces any useful error messages:
```
$ cd somewhere
$ git clone https://github.com/California-Planet-Search/radvel.git
$ cd radvel
$ python setup.py install
```
then test `radvel` again to see if you still see the warning message about the C extension.

**Comment by bjfultn** [comment]
Closing this stale issue until is crops up again.
