### ISSUE TITLE
Try/except clauses in GP Kernels

### ISSUE THREAD

**Issue by bjfultn** [California-Planet-Search/radvel#138]
@sblunt This is a low priority issue, but could you update the try/except clauses in the GP code to be more specific. e.g.:

```
try:
    do some stuff
except NameError:
    do some different stuff
```
instead of 
```
try:
    do some stuff
except:
    do some different stuff
```

catch-all except clauses are always bad practice in Python.

**Comment by sblunt** [comment]
@bjfultn addressed in pull request #143.
