### ISSUE TITLE
Error if output directory doesn't already exist - cli.py

### ISSUE THREAD

**Issue by sinukoff** [California-Planet-Search/radvel#158]
When the output directory doesn't already exist, I get: 
>> UnboundLocalError: local variable 'outdir' referenced before assignment
 
Lines 178-179 of cli.py read:
if not os.path.isdir(args.outputdir):
    os.mkdir(outdir)

This is problematic because outdir only gets defined if args.outputdir is None, so if the user specifies an output directory that doesn't already exist then outdir won't get defined, resulting in the error above.

I think lines 178-179 should be changed to: 
if not os.path.isdir(args.outputdir):
    os.mkdir(args.outputdir)

**Comment by bjfultn** [comment]
This will be fixed in pull request #159 (version 1.1.7).
