### ISSUE TITLE
Initial positions of MCMC walkers have incorrect scales

### ISSUE THREAD

**Issue by andrewwaynemayo** [California-Planet-Search/radvel#166]
In version 1.1.7, when the radvel.mcmc function determines initial positions of walkers it first assesses "pscales" on lines 145-162 of the mcmc.py file. Then a deep copy of the posterior object is created in line 167. However, this deep copy does not necessarily preserve the order of parameters (nor is it meant to, since dictionaries are not ordered). With a new ordering of parameters the pscales no longer match up with the correct parameters and the distribution of initial walker positions in each dimension can be much larger or smaller than intended.

**Comment by bjfultn** [comment]
I just removed the `deep copy` call in `mcmc.py` without adverse affects. @andrewwaynemayo you could check out and manually install the `next-release` branch to see if that fixes your issue. This fix will formally be released in the v1.1.8 release which may take a few days/week to get out.

@sblunt will this solve the issue though? For example, if we make deepcopies of the post.params attribute (which is what we usually need) won't we run into the same issue?

**Comment by sblunt** [comment]
We usually need attributes of `post.params`, right? Like `post.params.get_vary_params()`. So if we make a `deepcopy` of `post.params.get_vary_params()` and the other attributes we need will that fix it?

**Comment by andrewwaynemayo** [comment]
Sorry for the delayed response. @bjfultn I manually installed the `next-release` branch as you suggested and it appears to be working correctly now.
