### ISSUE TITLE
The table of RVs in the output pdf are different than the input txt file

### ISSUE THREAD

**Issue by kosiarek** [California-Planet-Search/radvel#175]
When I run RadVel, the output pdf has values offset in the table of RVs compared to the input txt file. For the case I'm running, there's HIRES and HARPS data. The HIRES datapoints are offset by about 1 m/s, the HARPS datapoints are offset by ~76 km/s (from 23 km/s to -53 km/s).

**Comment by kosiarek** [comment]
Here is the output file and input txt file. 
[testcirc_gp_binhires_20180418_results.pdf](https://github.com/California-Planet-Search/radvel/files/1925616/testcirc_gp_binhires_20180418_results.pdf)
[all_binhires_notharps_20180416.txt](https://github.com/California-Planet-Search/radvel/files/1925617/all_binhires_notharps_20180416.txt)

**Comment by bjfultn** [comment]
Thanks for the bug report @kosiarek. Could you also provide your setup file? Do you see this same thing if not using GPs? Is this simply a matter of the gammas being subtracted (which probably shouldn't be)?

**Comment by sblunt** [comment]
I found the issue. In like 123 of likelihood.py, the initial guesses for the gamma parameters are subtracted from the RVs. This is fine for the way radvel fits in general, but we need a way to make the table at the end correctly. Maybe we can just make the table using the config file instead of the likelihood object?

**Comment by sblunt** [comment]
Wait, actually we can fix this just by removing the subtraction of gamma in the `CompositeLikelihood`. The `RVLikelihood` and `GPLikelihood`s subtract off gamma in their residuals calculations, so there's no reason the `CompositeLikelihood` needs to subtract off a gamma. I'll fix it and pull request.

**Comment by bjfultn** [comment]
Great, thanks @sblunt. Assigning to you to close when complete

**Comment by bjfultn** [comment]
Bugfix adressed in pull request #176 will be released in v1.1.11
