### ISSUE TITLE
Mislabeled data frame

### ISSUE THREAD

**Issue by sharonxuesong** [California-Planet-Search/radvel#182]
Hi BJ and Erik and all,

It appears that if you have the parameters in the posterior object arranged in a non-default order, the result data frame returned by MCMC would have wrong labels... For example, my post object looks like this:
parameter                     value      vary
per1                        0.50557      False
per2                        4.56417      False
dvdt                              0      False
curv                              0      False
gamma                      0.301368       True
jit                        0.690656       True
tc1                         17582.8      False
tc2                         17580.7      False
secosw1                          -0      False
sesinw1                          -0      False
logk1                     -0.693147      False
secosw2                          -0      False
sesinw2                          -0      False
logk2                       1.21514       True

But then, in the returned data frame by mcmc, the three free parameters/chains are labeled as "gamma, jitter, logk" (i.e. in the same order as above), but they are actually "logk, gamma, jitter", which looks like it's following some sort of default order the same as given in the example in the documentation.

FYI codes here:
https://colab.research.google.com/drive/1kk6wBolRexLbJ2pzsmEAQyGSH9MEb6bb

**Comment by bjfultn** [comment]
Hi @sharonxuesong,

Thanks for the bug report.

I've tracked the issue down to have to do with multithreading. Apparently, OrderedDictionaries are not really ordered when sent to different child processes. I think @sblunt has run into this issue as well.

For now you can use the `serial=True` flag in your `radvel.mcmc` call to turn off multithreading. I'll continue to work on a solution.

**Comment by sharonxuesong** [comment]
Hi BJ,

Wow cool! Thank you for your prompt reply!
That totally worked and fixed the issue.

Cheers,
Sharon

**Comment by bjfultn** [comment]
A fix for this will be deployed in the version 1.1.12 release. See PR #183

**Comment by sblunt** [comment]
Yes, I've run into that issue as well. I was going to suggest that it's an issue with pickling objects inheriting from `OrderedDict`, since that's something that happens in copying and multithreading, but seems like you already figured that out, BJ. Thanks for tracking this down!!
