### ISSUE TITLE
possible error in BIC calculation

### ISSUE THREAD

**Issue by petigura** [California-Planet-Search/radvel#184]
Currently the BIC and AIC are methods of the posterior objects. 

But according to [wikipedia](https://en.wikipedia.org/wiki/Bayesian_information_criterion), it only depends on the likelihood and is independent of prior. Should we move the code and have people access it ala

```
like.bic()
like.aic()
```

**Comment by bjfultn** [comment]
@smmills Is this right? We should not be including the prior penalty term in our BIC/AIC calculations?

**Comment by bjfultn** [comment]
OK, I moved the bic and aic methods into the likelihood object and updated `model_comp` to call `fittest.likelihood.bic()` instead of `fittest.likelihood.bic()`. See commit fa42647. Will be released in v1.2.1.
