### ISSUE TITLE
bimodal jitter (+/-)

### ISSUE THREAD

**Issue by sinukoff** [California-Planet-Search/radvel#19]
Fit sqrt(jitter) instead?  In some cases, posterior peaks at +N and -N, averages to zero.

**Comment by bjfultn** [comment]
This issue has cropped up again. The included HD164922 example is producing a bimodal distribution for the APF jitter value.

**Comment by bjfultn** [comment]
Removing the sign-flipping hack I employed before fixes this for the HD164922 example. I'm going to remove that and leave it to the users to implement the appropriate priors and interpret the results accordingly.
