### ISSUE TITLE
Rounding/Uncertainties for Fixed Parameters in Plots

### ISSUE THREAD

**Issue by smmills** [California-Planet-Search/radvel#193]
When I fix a parameter (e.g., period), the rv_multipanel.pdf plot gives uncertainties on the fixed parameter consistent with rounding errors on double floating point numbers rather than printing the fixed value as a constant. Example attached. 

<img width="375" alt="screen shot 2018-09-15 at 12 19 55 pm" src="https://user-images.githubusercontent.com/8051246/45589839-03c28700-b8e2-11e8-9723-1c5ec4c6e7f0.png">

**Comment by bjfultn** [comment]
Should be fixed in commit 2b36285. Will be released in v1.2.1
