### ISSUE TITLE
Add Ability to Pause and Continue MCMC runs

### ISSUE THREAD

**Issue by bjfultn** [California-Planet-Search/radvel#195]
This would be a really useful feature for long/complex MCMC runs.

**Comment by sealauren** [comment]
I vote for adding this ability.

**Comment by bjfultn** [comment]
Leaving this for radvel version 2 release which will feature an overhaul of the MCMC (and maybe also MAP) backend(s)

**Comment by zhexingli** [comment]
Just saw this... I think it would be an extremely useful feature to have.

**Comment by bjfultn** [comment]
This is implemented as of v1.3.2
