### ISSUE TITLE
too many radial velocity data points hangs radvel

### ISSUE THREAD

**Issue by plavchan** [California-Planet-Search/radvel#201]
If a RV time-series file has on the order of 1000s of measurements, then the report pdf compilation hangs because a pdflatex user question is generated, because the RV table in latex is "more than 19 feet" long, something deluxetable can't handle.  Specifically, it hangs on this line of report.py on the first call to pdflatex:

proc.communicate() 

(around line 147 of report.py in compile() ).

Commenting out the latex generation of the RV time-series table in line 100 of report.py in texdoc():

        reportkw['tab_rv'] = textable.tab_rv()

solves this pdflatex hanging and the report generates without the RV time-series file.  Recommended solution is to do a check on the length of the RV time-series file, and if more than a certain number of data points, truncate the latex table, or eliminate it from the report entirely.

**Comment by bjfultn** [comment]
Thanks for the bug report! This is addressed in PR #202 and will be released shortly in version 1.2.3.
