### ISSUE TITLE
Remove gamma terms from MCMC

### ISSUE THREAD

**Issue by bjfultn** [California-Planet-Search/radvel#203]
Timothy Brandt showed that it is possible to solve for the gamma terms analytically given a set of other orbital parameters. See attached derivation. We could remove these terms from the MCMC free parameters and gain some speedup. 

[Marginalizing_the_likelihood.pdf](https://github.com/California-Planet-Search/radvel/files/2507649/Marginalizing_the_likelihood.pdf)

**Comment by bjfultn** [comment]
I implemented this on the `linear-gammas` branch such that if the gamma parameters have `vary==False` I set the gamma parameters equal to z_tilde from Equation 5 and multiply the logprob by sqrt(2*pi*sigma_z) where sigma_z is from Equation 8. If `vary==True` then the behavior should be the same as before. 

I still need to add calculation and interpretation of the analytical posteriors.

The HD164922 sample seems to converge about 30-40% faster with this technique.

**Comment by bjfultn** [comment]
I'm not sure how to apply this to the GP Likelihoods.

**Comment by leerosenthalj** [comment]
For GPs, would it be enough to instantiate a value of the Gaussian process at every t_obs, then fold those into the model-RV term?

**Comment by bjfultn** [comment]
I don't think so. The likelihood is completely different and there isn't really one value of the GP for a given set of GP hyper parameters, its a distribution.

**Comment by bjfultn** [comment]
@leerosenthalj there is a little more work to do to incorporate these results into the output products so I'm not going to release this with v1.2.5. Feel free to clone this branch and run with it if you want the speedup now.

**Comment by leerosenthalj** [comment]
Sounds good. I can also try to implement the gamma and gamma-dot
linearization, much simpler without gamma-doubledot. We could eventually
work on Keplerian/sinusoidal linearization on this branch too.
