### ISSUE TITLE
Semi-major axis values not produced in corner plot

### ISSUE THREAD

**Issue by zhexingli** [California-Planet-Search/radvel#211]
One of the derived parameter: semi-major axis of the planet(s) sometimes is not produced in the corner plot after running the derive command. It is only shown in the corner plot when I specify planetary radius in the setup file. It would be nice if semi-major axis could be shown no matter if we specify planetary radius because it's not dependent on radius.
This corner plot is produced when radius (a random number) is specified (semi-major axis is on it):
[HD118475_corner_derived_pars.pdf](https://github.com/California-Planet-Search/radvel/files/2838537/HD118475_corner_derived_pars.pdf)
This corner plot is produced when no radius is given (no semi-major axis info):
[HD118475_corner_derived_pars.pdf](https://github.com/California-Planet-Search/radvel/files/2838542/HD118475_corner_derived_pars.pdf)

The only difference between the two setup files that produced these two derived corner plots is the availability of planetary radius. Same problem for multi-planet fit.

**Comment by bjfultn** [comment]
Fixed in commit 78ca42f and will be released in v1.2.5
