### ISSUE TITLE
Drop Python 2.X Support

### ISSUE THREAD

**Issue by bjfultn** [California-Planet-Search/radvel#212]
When should we drop support for Python 2? If we want to upgrade the MCMC backend to emcee3, pymc3/pymc4 then I don't think those dependencies support Python 2 anymore. It would probably make sense to drop Python 2 support from `radvel` when we make that switch.

Does anyone have strong feelings that we must retain Python 2 support for the time being?

**Comment by bjfultn** [comment]
I'm starting to see warnings like this:
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
```

**Comment by zhexingli** [comment]
I support the decision to drop python 2.X.

**Comment by petigura** [comment]
I don't have strong feeling about retaining support for python2. However, I would advocate for making it clear which github version is the last stable python2 release.

**Comment by bjfultn** [comment]
Python 2 support has been dropped as of version 1.2.12. I have not made any changes to specifically make radvel incompatible with Python 2.7, but I make no guarantees going forward.
