### ISSUE TITLE
Annoying Warnings

### ISSUE THREAD

**Issue by bjfultn** [California-Planet-Search/radvel#214]
Resolve issues producing all of the many warnings seen when running `radvel`. Here is a list of a few that I see. Lets get rid of as many of these as possible. Some are likely outside of our control due to packages that are dependencies. Please feel free to post any other warnings that you see as well.

- ~~invalid escape sequence \s~~

- ~~Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working~~ pre-importing `emcee` and nbsphinx gets rid of these warnings

- invalid value encountered in true_divide

- ~~/Users/bjfulton/anaconda3/lib/python3.6/site-packages/celerite-0.3.0-py3.6-macosx-10.7-x86_64.egg/celerite/solver.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses~~ this seems to be fixed if all dependencies are up to date

- can't resolve package from __spec__ or __package__, falling back on __name__ and __path__

- invalid value encountered in double_scalars

- ~~the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.~~

- Non-positive definite kernel detected.

- `nbconvert.exporters.exporter_locator` is deprecated in favor of `nbconvert.exporters.base` since nbconvert 5.0.

- Traits should be given as instances, not types (for example, `Int()`, not `Int`). Passing types is deprecated in traitlets 4.1.

**Comment by leerosenthalj** [comment]
pythonpath/site-packages/scipy/optimize/optimize.py:1927: RuntimeWarning: invalid value encountered in double_scalars

**Comment by smmills** [comment]
```
RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
```

```
ImportWarning: celerite not installed. GP kernals using celerite will not work.
Try installing celerite using 'pip install celerite'
  Try installing celerite using 'pip install celerite'", ImportWarning)
```
^ This warning is OK, but it doesn't need to be three lines long. 

```
SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  vec[vec >= np.radians(0)] = vec[vec >= np.radians(0)] - np.radians(360)
```

```
RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
```

**Comment by bjfultn** [comment]
fixed most escape sequence warnings

**Comment by bjfultn** [comment]
fixed numpy matrix warning

**Comment by bjfultn** [comment]
removed the extra newline in the celerity ImportWarning

**Comment by bjfultn** [comment]
I think I've been able to hide the `spicy.optimize` `RuntimeWarning`

**Comment by bjfultn** [comment]
I think I've worked around the pandas `SettingWithCopyWarning`

**Comment by leerosenthalj** [comment]
Excellent. Those `spicy` warnings are a real hassle.

**Comment by bjfultn** [comment]
Fixes are live in v1.2.5. @smmills and @leerosenthalj please try it out.

**Comment by smmills** [comment]
```
$ radvel --version
/Users/seanmills/radvel_process/radvel_process_env/lib/python3.7/site-packages/radvel/gp.py:33: ImportWarning: celerite not installed. GP kernals using celerite will not work. Try installing celerite using 'pip install celerite'
  Try installing celerite using 'pip install celerite'", ImportWarning)
numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
RadVel 1.2.5
```

**Comment by bjfultn** [comment]
To summarize, here are the remaining warnings I know about (for a clean environment and a fresh install from pypi).

- `/Users/bfulton/anaconda3/envs/jump/radvel/lib/python3.7/site-packages/radvel/gp.py:33: ImportWarning: celerite not installed. GP kernals using celerite will not work. Try installing celerite using 'pip install celerite'` - still multiple lines! need to remap the default `warnings.warn` messages, or better yet switch our warnings over to `logger`

- `numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject` - still don't know what to do about this one

**Comment by smmills** [comment]
Semi-relevant (and not worthy of a new thread): During the MCMC, lines like 
```
0000/4000000 (0.5%) steps complete; Running 19002.19 steps/s; Mean acceptance rate = 41.5%; Min Tz = -1.0; Max G-R =   inf     
```
seem to end in carriage return (\r) but no newline (\n). This is fine if printing to a terminal, but if you try to save the output for later triage it can make the the resulting text documents unwieldy.

**Comment by bjfultn** [comment]
True, I'm staged to move to using `curses` to display a whole separate screen while running MCMC in PR #210. Which is better in some ways, and worse in others. Probably also need to add a flag to turn on/off the progress messages.

**Comment by bjfultn** [comment]
I'm actually not seeing any of these annoying warnings anymore. Specifically the `numpy.ufunc` warning that I couldn't figure out. I suspect that this was fixed in one or more updates from the dependencies.
