### ISSUE TITLE
HardBounds prior with upper bound of infinity

### ISSUE THREAD

**Issue by smmills** [California-Planet-Search/radvel#216]
If I want to restrict a certain parameter to strictly positive values, I would think I could do so by using:
```
radvel.prior.HardBounds('k1', 0., np.inf)
```
but this seems to cause the likelihood to malfunction. I am aware this is an improper prior, however, the code works fine if I use no prior at all, which is also improper. 

A current workaround is to use 1e10 or some large number in place of np.inf, but I'm not sure this is ideal.

**Comment by bjfultn** [comment]
In this case you want to use the `PositiveKPrior` unless you don't want to force K>0 for all planets in the system.

Still, this should probably work.

**Comment by bjfultn** [comment]
Why do we return -np.log(self.maxval-self.minval) if the parameter is inside the bounds? Shouldn't we return 0 when inside the bounds and `-np.inf` when outside?

```
def __call__(self, params):
        x = params[self.param].value
        if x < self.minval or x > self.maxval:
            return -np.inf
        else:
            return -np.log(self.maxval-self.minval)
```

**Comment by smmills** [comment]
Ah, somehow I missed that in the priors list. That clearly seems like the proper thing for the example I showed (though you might want similar functionality for parameters besides K).

**Comment by smmills** [comment]
re: returning -np.log(self.maxval-self.minval):
This is the correct normalization of the likelihood such that it yields the probability of the model given the data rather than just the likelihood, if all priors are properly normalized. That is, it correctly penalizes the likelihood by the broadness of the prior.

**Comment by bjfultn** [comment]
Got it, thanks.

So should we put in a hack that returns a non-normalized version if an inf bound is provided? Or just a warning/assertion that both bounds be finite?

**Comment by smmills** [comment]
I would lean towards the former, because it does what a normal user intrinsically wants (you might even print out a warning suggesting the PositiveKPrior as an alternative for noobs like me!). 

If someone is actually trying to compute P(Model | Data) and do some Evidence calculations or whatnot, they will already know they can't have improper priors I would guess so this extra permissiveness wouldn't hurt them.

**Comment by bjfultn** [comment]
Added warnings and allow for non-finite boundaries in PR #215. Will release in v1.2.5 (hopefully today).
