### ISSUE TITLE
Why RadVel sometimes doesn't show red binned data on rv multipanel plots?

### ISSUE THREAD

**Issue by zhexingli** [California-Planet-Search/radvel#222]
For most cases the red binned data are shown on the phased planetary orbit fit in rv multipanel plots, sometimes doesn't. Why is that?

Here's a plot that shows the binned data:
[HD212330_rv_multipanel.pdf](https://github.com/California-Planet-Search/radvel/files/2862477/HD212330_rv_multipanel.pdf)

Here's a plot that doesn't show the binned data:
[HD118475_rv_multipanel.pdf](https://github.com/California-Planet-Search/radvel/files/2862468/HD118475_rv_multipanel.pdf)

**Comment by bjfultn** [comment]
Binning is activated only if the number of measurements is >= 20. You can force it off by setting `nobin==True` in the [MultipanelPlot](https://radvel.readthedocs.io/en/latest/orbit_plots.html#radvel.plot.orbit_plots.MultipanelPlot)
