### ISSUE TITLE
Y axis not showing enough range

### ISSUE THREAD

**Issue by zhexingli** [California-Planet-Search/radvel#227]
Just trying to do a random fitting, but what's happening to this? Y axis not showing the entire data and curve.
[HD92987_rv_multipanel.pdf](https://github.com/California-Planet-Search/radvel/files/2882206/HD92987_rv_multipanel.pdf)

Is changing yscale to auto the only way? It's using the default option now.

**Comment by bjfultn** [comment]
This happens with the amplitude of the signal is larger than the range of the data being plotted. Try adding the `--plotkw "{'yscale_auto': True}"` flat to your `radvel plot` call.

**Comment by zhexingli** [comment]
> This happens with the amplitude of the signal is larger than the range of the data being plotted. Try adding the `--plotkw "{'yscale_auto': True}"` flat to your `radvel plot` call.

I see, and yep, letting it autoscale works now. Thanks.
