### ISSUE TITLE
RadVel having trouble generating summary pdf after the new update

### ISSUE THREAD

**Issue by zhexingli** [California-Planet-Search/radvel#230]
I'm having issue generating the final result pdf file. After I type in 'radvel report -s [filename]', then the command line just seems stop running and stays in 'stopped' state like this:
<img width="583" alt="screen shot 2019-03-01 at 11 33 59" src="https://user-images.githubusercontent.com/18060088/53661823-33f2ad80-3c16-11e9-8020-a159ba3d000f.png">

I've never had this issue before. This came up after I updated my local RadVel to include the changes on adding derived tables in the final result file.

Any ideas?

**Comment by bjfultn** [comment]
Is the `.tex` version of the report being produced? If so, try compiling that manually outside of radvel and seeing what errors are produced.

**Comment by zhexingli** [comment]
Here are the error messages:
<img width="761" alt="screen shot 2019-03-01 at 11 43 49" src="https://user-images.githubusercontent.com/18060088/53662284-6355ea00-3c17-11e9-981b-19ead71a82d7.png">
<img width="763" alt="screen shot 2019-03-01 at 11 44 04" src="https://user-images.githubusercontent.com/18060088/53662288-66e97100-3c17-11e9-89e4-efdcb64da90c.png">

Not sure which ones are causing this problem. Before having this problem, radvel was still able to produce a pdf summary file even though latex had been giving error messages to almost all the .tex file after compiling.

**Comment by bjfultn** [comment]
Do you have underscores in your instrument names, and which version of RadVel are you running?

**Comment by zhexingli** [comment]
No underscores in instrument names. The version should be the most up-to-date one, I just updated is last night.

**Comment by bjfultn** [comment]
Would you mind e-mailing me that .tex version of the report so I can have a quick look?

**Comment by zhexingli** [comment]
Sure. Sent.

**Comment by bjfultn** [comment]
Fixed with a re-install in a clean environment.
