### ISSUE TITLE
Model comparison failing

### ISSUE THREAD

**Issue by zhexingli** [California-Planet-Search/radvel#232]
I was running RadVel on a 3 planet model: 47 UMa. But in the end it appears there's an issue relating to model comparison. Again, I've never had this issue before and this is completely new to me.

So when I ran "radvel ic -t nplanets e trend -s [filename]", no error messages, just a bunch of warnings like this:
<img width="570" alt="screen shot 2019-03-05 at 00 34 37" src="https://user-images.githubusercontent.com/18060088/53791918-5ff48400-3edf-11e9-9922-50bd1b05d884.png">

Then when I ran "radvel table -t params priors ic_compare derived -s [filename]", error messages start to pop up:
<img width="567" alt="screen shot 2019-03-05 at 00 26 27" src="https://user-images.githubusercontent.com/18060088/53791910-5b2fd000-3edf-11e9-9af3-72b840bd2fe3.png">

And finally when I ran "radvel report -s [filename]", I had error messages:
<img width="568" alt="screen shot 2019-03-05 at 00 38 36" src="https://user-images.githubusercontent.com/18060088/53791840-3176a900-3edf-11e9-8c91-9c10463449dc.png">

Apparently the model comparison table is not displayed. I had no issue about this at all before this. Not sure if it's a general problem or just for this specific multi-planet fit.

**Comment by bjfultn** [comment]
Something is going wrong with the model comparisons that is putting NaNs in that table. Try running them one at a time (e.g. `radvel ic -t nplanets`), to see which part is causing it. 

BTW: You don't explicitly need to run the `radvel` table command unless you need those tables as separate .tex documents. Otherwise `radvel report` will automatically generate all of the tables that it can.

**Comment by zhexingli** [comment]
Earlier when 'radvel ic [...]' was failing the summary report doesn't have model comparison table in it. Now I just ran the 'radvel ic commands separately and interestingly no error occurred. I guess better run the command separately next time rather than all in one command?

**Comment by bjfultn** [comment]
Its being tested with multiple ic commands at once, but its possible something weird is going on with this particular fit. Since infs or nana are being put into that table I suspect it has something to do with certain models being extremely favored or disfavored.

**Comment by zhexingli** [comment]
I see. Thank you!

**Comment by bjfultn** [comment]
I think that this was due to peculiarities in the data and/or fit results rather than a bug in the code. Closing until we show otherwise.
