### ISSUE TITLE
New way for Mpsini determination

### ISSUE THREAD

**Issue by zhexingli** [California-Planet-Search/radvel#235]
We've raised this concern to BJ a while ago about solving the secondary mass in a binary system. The current RadVel method for calculating Mpsini is based on the assumption that Mpsini << Mstar, which will lead to a different mass result when dealing with binary. So for RadVel to work on our projects, I changed how Mpsini is calculated. Now it no longer assumes Mpsini << Mstar, instead it simply calculates the mass numerically using the RV semi-amplitude equation and results from MCMC. I've been hesitating about posting it here, but so far it's proving to be working well. The change is simple, you may decide to use it or not. Take a look. Here it is:

1. add "from scipy.optimize import root" at the top of util.py file.

2. In the definition Mpsini, now the code looks like this:
def Msini(K, P, Mstar, e, Msini_units='earth'):
  
    P = np.array(P)
    Mstar = np.array(Mstar)
    K = np.array(K)
    e = np.array(e)
    G = c.G.value                # added gravitational constant
    Mjup = c.M_jup.value         # added Jupiter's mass
    Msun = c.M_sun.value         # added sun's mass

    P = (P * u.d).to(u.second).value
    Mstar = Mstar*Msun
       
    a = K*(((2*(np.pi)*G)/P)**(-1/3))*np.sqrt(1-(e**2))
    Msini = []
    for i in range(len(P)):
        def func(x):
            return x - a[i]*((Mstar[i]+x)**(2/3))
        sol = root(func,Mjup)
        Msini.append(sol.x[0])
   
    Msini = np.array(Msini)
    Msini = Msini/Mjup
   
    if Msini_units.lower() == 'jupiter':
        pass 
    elif Msini_units.lower() == 'earth':
        Msini = (Msini * u.M_jup).to(u.M_earth).value
    else:
        raise Exception("Msini_units must be 'earth', or 'jupiter'")

    return Msini

3. In the driver.py file, in the definition derive, right below the lines where you put a warning flag about mass implicit assumption, added this line:
mtotal = mstar + (mpsini*c.M_earth.value)/c.M_sun.value      # get total star plus planet mass
and also edited the line below it:
a = radvel.utils.semi_major_axis(per, mtotal)               # changed from mstar to mtotal

Now it's capable of solving secondary mass in a binary system, but the 'radvel derive -s [filename]' command is slightly slower than before, as expected, because the code is solving for mass numerically.

Github is doing some weird display here..

**Comment by bjfultn** [comment]
Thanks @zhexingli! Could you submit this as a pull request?
1. Fork the repo
1. Clone your fork of the repo
1. Create a branch for this change
1. Use the GitHub web interface to submit a pull request from your new branch into `next-release`

**Comment by zhexingli** [comment]
Done. Could you check if everything looks ok? There's one more fix I couldn't do on my end without causing radvel to run into troubles. I noted in the pull request. If you could help fix that, it would be great. Thx.

**Comment by bjfultn** [comment]
Yep, everything looks ok in PR #236
