### ISSUE TITLE
Cython error on clean install

### ISSUE THREAD

**Issue by iancrossfield** [California-Planet-Search/radvel#237]
On my new machine, `pip install radvel` leads to the following error.  (pip v18.1, Python 3.7):

`Collecting radvel
  Downloading https://files.pythonhosted.org/packages/0b/a4/d2bb975627c7ddc0a0a6c0dfa79d023aad5372cbb38a6f4e7e26ba055cca/radvel-1.2.8.tar.gz (186kB)
    100% |████████████████████████████████| 194kB 10.9MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-oisye4eg/radvel/setup.py", line 3, in <module>
        import Cython.Build as cb
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-oisye4eg/radvel/
`

**Comment by iancrossfield** [comment]
The issue was successfully solved by first doing a separate cython install:
`pip install cython`
which installed  cython-0.29.6.  After that, `pip install radvel` worked like a charm.

**Comment by bjfultn** [comment]
Thanks for the bug report @iancrossfield. This should be fixed in PR #238 and version release 1.2.9. I also updated the documentation to suggest that a scientific Python environment such as Anaconda or Miniconda is installed before attempting to `pip install radvel`.
