### ISSUE TITLE
Negative Jitters (even with hardbound prior)

### ISSUE THREAD

**Issue by kosiarek** [California-Planet-Search/radvel#240]
I'm finding jitter posteriors symmetric around zero in corner plots (which affects the posterior value of the jitter) even when setting a HardBound prior on it from 0-15 m/s. Example attached. 
[circ_2pl_20190405_results.pdf](https://github.com/California-Planet-Search/radvel/files/3055785/circ_2pl_20190405_results.pdf)

**Comment by bjfultn** [comment]
I just confirmed that this is fixed in v1.2.8. Upgrade to that version via `pip install radvel --upgrade`. Please re-open this issue if you still see it there.
