### ISSUE TITLE
bug in msini code

### ISSUE THREAD

**Issue by sealauren** [California-Planet-Search/radvel#247]
Traceback (most recent call last):
  File "KGPS_generalized.py", line 195, in <module>
    print_masses(like.params, mstar)
  File "KGPS_generalized.py", line 86, in print_masses
    msini = radvel.utils.Msini(params['k'+str(i+1)].value, params['per'+str(i+1)].value, mstar, 0.0, Msini_units='earth')
  File "/Users/lweiss/radvel/radvel/utils.py", line 563, in Msini
    **if (((Msini * u.Mjup).to(u.M_sun) / (Mstar/Msun)).value > 0.1).any():**
AttributeError: 'bool' object has no attribute 'any'

**Comment by bjfultn** [comment]
Version 1.2.9? And your inputs are all floats (not arrays)?

**Comment by sealauren** [comment]
Yes they are all float inputs.  I think there is a parenthesis misplacement in the line I bolded.  I am on 
RadVel 1.2.10

**Comment by sealauren** [comment]
`In [1]: import radvel                                                                                                             
rnumpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

In [2]: radvel.__version__                                                                                                        
Out[2]: '1.2.10'

In [3]: msini = radvel.utils.Msini(0.1, 365.25, 1.0, 0.0, Msini_units='earth')                                                    
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-f054e7d60a11> in <module>
----> 1 msini = radvel.utils.Msini(0.1, 365.25, 1.0, 0.0, Msini_units='earth')

~/radvel/radvel/utils.py in Msini(K, P, Mstar, e, Msini_units)
    561 
    562     # Use correct calculation if any elements are >10% of the stellar mass
--> 563     if (((Msini * u.Mjup).to(u.M_sun) / (Mstar/Msun)).value > 0.1).any():
    564         print("Mpsini << Mstar assumption broken, correcting Msini calculation.")
    565 

AttributeError: 'bool' object has no attribute 'any'

`

**Comment by bjfultn** [comment]
No, that function needs to work with arrays, and it does, but I guess it didn't get tested with floats. Work-around for now would be to turn your inputs into arrays.

**Comment by sealauren** [comment]
It seems to be working with arrays:

In [12]: msini = radvel.utils.Msini([12], [11.86 * 365.25], [1.0], [0.0], Msini_units='jupiter')                                  

In [13]: print(msini)                                                                                                             
[0.96247247]

**Comment by sealauren** [comment]
the function could be adjusted to check if each variable is iterable; if not, make it one

**Comment by bjfultn** [comment]
Or a check if the input is a float and then do a different `if` statement. There are several easy to handle this I'm sure. Speed is not that important because this is only called when deriving parameters.

Submit a PR?

**Comment by bjfultn** [comment]
Adressed in PR #248. Will continue discussion there if needed. Thanks @sealauren!
