### ISSUE TITLE
Can't run RadVel after new updates

### ISSUE THREAD

**Issue by zhexingli** [California-Planet-Search/radvel#254]
Now running radvel it returns this error message:
"""
Traceback (most recent call last):
  File "/Users/ZhexingLi/anaconda/bin/radvel", line 6, in <module>
    from radvel.cli import main
  File "/Users/ZhexingLi/anaconda/lib/python3.6/site-packages/radvel/__init__.py", line 7, in <module>
    from .model import *
  File "/Users/ZhexingLi/anaconda/lib/python3.6/site-packages/radvel/model.py", line 4, in <module>
    from radvel import kepler
  File "/Users/ZhexingLi/anaconda/lib/python3.6/site-packages/radvel/kepler.py", line 7, in <module>
    from . import _kepler
  File "__init__.pxd", line 918, in init radvel._kepler
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
"""

I believe I upgraded my astropy and downloaded Orbitize and other stuff before this error.

Help please?

Thanks

**Comment by sblunt** [comment]
Hey Zhexing! I’ll try to get you out of this mess since I got you into it.

I think it makes sense to upgrade RadVel. Just try “pip install radvel —upgrade” in the command line. Let me know how it goes.

**Comment by zhexingli** [comment]
Hey Sarah! Thanks for offering to help. Yes I tried to uninstall radvel and
reinstall it, yet the problem persists. I even tried to uninstall orbitize
(sorry! had to try it) and xcode but doesn't matter. Based on the error
message, seems like numpy is having problem with it? But I don't recall we
upgraded numpy at the DC.

Zhexing

**Comment by sblunt** [comment]
Ok, let’s try a full install from the beginning then. You can do it in a conda virtual environment to be safe. Try:

“conda create -n radvel-test python=3.6 numpy scipy astropy matplotlib cython”

Then:

“conda activate radvel-test”
“pip install radvel”

Then try running some RadVel code. Let me know if that works.

**Comment by zhexingli** [comment]
Yup it's working in that test environment! So it's the version issues and
radvel doesn't support the latest packages?

Zhexing

**Comment by sblunt** [comment]
Great! When you installed everything from scratch in the test environment it automatically grabbed the latest versions of everything, so I think something in your root conda environment (maybe numpy, as you suggested) is just a very old version. I suggest updating all of the radvel dependencies in your root conda environment, then reinstalling radvel (and orbitize, and anything else that has similar dependencies). This should do the trick:

`conda deactivate
conda upgrade numpy scipy astropy matplotlib cython
pip uninstall corner emcee radvel orbitize
pip install corner emcee radvel orbitize`

Fingers crossed!

**Comment by zhexingli** [comment]
Nice it's running! Thank you! But it gives this warning message:
'numpy.ufunc size changed, may indicate binary incompatibility. Expected
192 from C header, got 216 from PyObject

HD164922.py'

**Comment by sblunt** [comment]
That’s normal. Congrats! Glad it’s working.

**Comment by zhexingli** [comment]
Thank you Sarah!!!
