### ISSUE TITLE
NameError: name 'inf' is not defined

### ISSUE THREAD

**Issue by pgorrini** [California-Planet-Search/radvel#255]
I was running RadVel on a 3 planet model. When I ran "radvel ic -t nplanets e trend -s filename.py" no error appears.

numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
filename.py

But when I ran "radvel table -t params priors ic_compare derived -s filename.py" this shows up:

numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
filename.py
Generating LaTeX code for params table
Generating LaTeX code for priors table
Generating LaTeX code for ic_compare table
Traceback (most recent call last):
  File "/home/paula/.local/bin/radvel", line 11, in <module>
    load_entry_point('radvel==1.2.11', 'console_scripts', 'radvel')()
  File "/home/paula/.local/lib/python2.7/site-packages/radvel/cli.py", line 176, in main
    args.func(args)
  File "/home/paula/.local/lib/python2.7/site-packages/radvel/driver.py", line 348, in tables
    compstats = eval( status.get('ic_compare', 'ic')) 
  File "<string>", line 1, in <module>
NameError: name 'inf' is not defined

I tried to do it separately "radvel table -t params -s filename.py", "radvel table -t priors -s filename.py" but when I got to "ic_compare" the same error appears.

I have ran "ic_compare" before and I didn't get this error. The first time everything worked ok but after modifying some parameters, the table only showed me the favoured model and not the others. And now it is not working.

**Comment by bjfultn** [comment]
This usually happens if the final fit is no good. Does the final best-fit model look like a good fit to the data?

**Comment by pgorrini** [comment]
Yes, it looks okay. I look at the rv plot before performing the mcmc, making sure that the fit looks good in the first place. But the posteriors plot does not look that good. So maybe the problem is with my fit? That's why I get this error?

**Comment by bjfultn** [comment]
I think so, ugly posteriors are a bad sign. If you are willing to share your setup file and data I could try diagnosing in more detail.

**Comment by pgorrini** [comment]
Yeah, that could be then. I will try to see if I can improve it. I am a master student so I'm kinda new to this. I will see the problem with my advisor and if I can't get it better I will contact you. Thank you so much for the fast reply and the good will!

**Comment by bjfultn** [comment]
Just wondering, were you able to make any progress on this? Or has it still got you stuck?

**Comment by pgorrini** [comment]
Yes, I realized that the problem was with the fit. But from mistakes we learn.
Thanks so much again :)
