### ISSUE TITLE
Does fitting for highly eccentric orbit require special configuration of radvel?

### ISSUE THREAD

**Issue by zhexingli** [California-Planet-Search/radvel#257]
I'm having such a hard time fitting this object:
[HD98649_rv_multipanel.pdf](https://github.com/California-Planet-Search/radvel/files/3455450/HD98649_rv_multipanel.pdf)
The fit looks fine, but MCMC just wouldn't converge no matter what I changed in the setup file. The max G-R statistics is nowhere near convergence when the chain is finished (near 1.1). Could this be due to the out-of-place binned data in the phase-folded plot? I tried to turn nobin = True on but I guess that's just for plotting not for fitting because that didn't help the MCMC fitting.

I have another system that also has a highly eccentric planet (e>0.8) and had a hard time fitting that too. For that system, there's also an out-of-place binned data, but that one is not as far from the model as the one shown here, so even though the fitting was tough, MCMC still managed to converge.

Any ideas what's going on here? Do I need to change anything in radvel? Thanks.

**Comment by bjfultn** [comment]
In general, high-eccentric fits are the same as any other fits.

This one is a bit tricky. It seems like `sesinw1` is unusually well constrained. By inspection of the trend plots I could see that the eccentricity parameters were being stubborn. I was able to get it to converge relatively quickly by manually setting the `mcmcscale` parameters for `secosw1` and `sesinw1` to 0.02. You might play around with these parameters a bit to see how the uncertainties change.

```
params['secosw1'].mcmcscale = 0.02
params['sesinw1'].mcmcscale = 0.02
```

I attach my results PDF. I made a couple other changes, but I think it was the `mcmcscale` parameters that made the difference.

@zhexingli if this works for you please update with anything else you've learned and close the issue.

[HD98649_results.pdf](https://github.com/California-Planet-Search/radvel/files/3458465/HD98649_results.pdf)

**Comment by zhexingli** [comment]
Ah ok, I didn't know I can do that in the setup file. I added mcmcscale for both parameters, didn't work, then added gaussian priors on P, Tc, and k to work with that. Now MCMC can converge, but only after some time, at ~70% of the maximum allowed number of steps. But it works! Thanks BJ!

Does this change the step size of the chain for those two parameters? What's the default step size for radvel?

**Comment by bjfultn** [comment]
Changing `mcmcscale` changes the initial step size in the MCMC chain. Ultimately, the step sizes adapt to the width of the posteriors as the likelihood surface is explored, but the size of the initial ball of walkers is also dictated by `mcmcscale` (if set). If the initial ball is too broad then convergence will be slow or impossible. I think thats what you are seeing here.

This is the code that sets up the initial spread:
```
    # set up perturbation size
    pscales = []
    for par in post.list_vary_params():
        val = post.params[par].value
        if post.params[par].mcmcscale is None:
            if par.startswith('per'):
                pscale = np.abs(val * 1e-5*np.log10(val))
            elif par.startswith('logper'):
                pscale = np.abs(1e-5 * val)
            elif par.startswith('tc'):
                pscale = 0.1
            else:
                pscale = np.abs(0.10 * val)
            post.params[par].mcmc_scale = pscale
        else:
            pscale = post.params[par].mcmcscale
        pscales.append(pscale)
    pscales = np.array(pscales)
```

So for most parameters it defaults to 10% of the parameter value.

I run hundreds of automated RadVel fits every day and I very rarely, if ever, have to adjust these parameters so hopefully you don't see this issue too often.

**Comment by zhexingli** [comment]
Got it. Thanks BJ!
