### ISSUE TITLE
Fetching final parameters

### ISSUE THREAD

**Issue by zhexingli** [California-Planet-Search/radvel#258]
This is not an issue, but really a question, might be silly to some coding experts...

I'm trying to automate radvel and I'm using python's 'subprocess' to do this in my python script.  Basically doing the same things as the command line commands, but instead do that in a python script so I can automate. Part of that effort is trying to let my script fetch the final orbital parameters (such as period, eccentricity etc) as those displayed in the final report and from the command line after running MCMC. Can someone show me the way please?

Thanks

**Comment by bjfultn** [comment]
You could load the `*_post_summary.csv` files if you just need the parameter quantiles, or you can load the `*_post_obj.pkl` file if you need anything else stored in the `Posterior` object.

**Comment by zhexingli** [comment]
Ok thanks.
