### ISSUE TITLE
problem with emcee calls through radvel.mcmc()

### ISSUE THREAD

**Issue by neilzim** [California-Planet-Search/radvel#262]
I am trying to run the tutorial notebooks on a fresh anaconda installation, with radvel version 1.2.13 and emcee version 3.0.0. Each notebook (e.g., docs/tutorials/164922_Fitting+MCMC.ipynb) fails on the call to radvel.mcmc(). It seems that emcee is expecting a different parameter:

```python
~/anaconda3/lib/python3.7/site-packages/emcee/backends/backend.py in get_value(self, name, flat, thin, discard)
     41     def get_value(self, name, flat=False, thin=1, discard=0):
     42         if self.iteration <= 0:
---> 43             raise AttributeError("you must run the sampler with "
     44                                  "'store == True' before accessing the "
     45                                  "results")

AttributeError: you must run the sampler with 'store == True' before accessing the results
```

**Comment by bjfultn** [comment]
I have not yet updated `radvel` to work with emcee 3. For now, `radvel` is only compatible with `emcee<=2.2.1`.

**Comment by neilzim** [comment]
Got it - I'll reinstall the older emcee then. Thanks.
