### ISSUE TITLE
Error message when runing mcmc

### ISSUE THREAD

**Issue by aberrico** [California-Planet-Search/radvel#273]
I' m having a deprecation_warning error in ensemble.py. I'm just trying to replicate the examples at the Getting Started page. This happens when I run this line:

df = radvel.mcmc(post,nwalkers=20,nrun=400)

line 86, in __init__
    self.pool = pool

NameError: name 'deprecation_warning' is not defined

**Comment by bjfultn** [comment]
What version of `radvel` and `emcee` are you using?

If you haven't tried this already I recommend trying to start from a clean conda environment and installing only the dependencies needed for radvel.

**Comment by aberrico** [comment]
radvel v1.2.13
emcee v2.2.1

I think the enviroment was clean enough, I made all the instalation to use radvel.

**Comment by bjfultn** [comment]
Thanks, could you also post the full traceback for this error?

**Comment by aberrico** [comment]
df = radvel.mcmc(post,nwalkers=20,nrun=400)
Traceback (most recent call last):

  File "<ipython-input-136-f05389febb48>", line 1, in <module>
    df = radvel.mcmc(post,nwalkers=20,nrun=400)

  File "C:\Users\Adriana\Anaconda3\lib\site-packages\radvel\mcmc.py", line 177, in mcmc
    statevars.nwalkers, statevars.ndim, post.logprob_array, threads=1))

  File "C:\Users\Adriana\Anaconda3\lib\site-packages\emcee\ensemble.py", line 86, in __init__
    self.pool = pool

NameError: name 'deprecation_warning' is not defined

**Comment by bjfultn** [comment]
It looks like the issue might be coming from emcee. Are you able to initialize an `emcee.EnsembleSampler` object outside of radvel (but in your radvel anaconda environment)?

**Comment by aberrico** [comment]
You're right,  I can't initialize the object. I uninstalled and reinstalled emcee and I have a different error now. Anyway, not a radvel problem so far.
Thanks

**Comment by bjfultn** [comment]
OK, good to hear.

Note that the current stable version of radvel is not compatible with emcee3 so if the reinstall upgraded emcee to the latest version then it won't work. I will release an update in the next few days which will work with emcee3. Let me know if you need emcee3 compatibility to proceed and I can create a release candidate of our dev version that you can pip install.
