### ISSUE TITLE
Keyerror while using GP 

### ISSUE THREAD

**Issue by SpaceyCaseyLynn** [California-Planet-Search/radvel#275]
Hi again, 
I've tried following the GP tutorial for k2-131, and keep getting the error "Keyerror: gp_amp" when I try to run the command "for tel in instnames: initialize(tel)". One time when I ran it, it worked, but every other time I get this error. I found the part in the source code that gives this error but can't figure out *why* it's happening. 

If you can let me know what's going on and how to fix it, that would be amazing. 

Thanks, 
Casey

**Comment by bjfultn** [comment]
Sounds like you have 'gp_amp' in the list of instrument names. Don't confuse `instnames` (list of instruments in the dataset) with `hnames` (dictionary of GP hyperparameters).

Instnames is defined in cell 2
```
data = pd.read_csv(os.path.join(radvel.DATADIR,'k2-131.txt'), sep=' ')

t = np.array(data.time)
vel = np.array(data.mnvel)
errvel = np.array(data.errvel)
tel = np.array(data.tel)

telgrps = data.groupby('tel').groups
instnames = telgrps.keys()
```

While `hnames` is defined in cell 4:
```
hnames = [
    'gp_amp', # eta_1; GP variability amplitude
    'gp_explength', # eta_2; GP non-periodic characteristic length
    'gp_per', # eta_3; GP variability period
    'gp_perlength', # eta_4; GP periodic characteristic length
]
```

**Comment by SpaceyCaseyLynn** [comment]
Hi BJ,
I did this (I pretty much copy and pasted the tutorial into a jupyter
notebook and just changed the file path but I'm pretty sure it's reading it
in properly).

Thanks,
Casey

**Comment by bjfultn** [comment]
Are you able to run the notebook included with the repo itself in `/docs/tutorials/`? This is the notebook that is used to generate that tutorial page.

**Comment by bjfultn** [comment]
Just checking in to see whether this was solved and can be closed?

**Comment by SpaceyCaseyLynn** [comment]
Yes, I was able to solve it!! Thank you so much.
