### ISSUE TITLE
Large output file size

### ISSUE THREAD

**Issue by petigura** [California-Planet-Search/radvel#279]
Thanks for implementing the autocorr time BJ. The default run time has gone up dramatically, as has the output file size. With the defaults, running the example from the documentation generated >100 MB of output files. What do you think about making the default to just save the 
"thinned" chains. Say every 10?

![image](https://user-images.githubusercontent.com/694371/68707100-f6387980-0545-11ea-9558-fef43c177e14.png)

 What do you think about setting the default to save the "thinned" chains.

**Comment by bjfultn** [comment]
This could also indicate that we are being too stringent with our new convergence criteria.

**Comment by bjfultn** [comment]
Changed default thinning to 10 for v1.3.1
