### ISSUE TITLE
trend plots look strange

### ISSUE THREAD

**Issue by petigura** [California-Planet-Search/radvel#280]
There is some weird periodic structure in some of the MCMC chain plots

![image](https://user-images.githubusercontent.com/694371/68708992-a360c100-0549-11ea-9053-0bd3c73b5fe6.png)

I'm wondering if there is an array reshaping error in:

```python
    def plot(self):
        """
        Make and save the trend plot as PDF
        """
        with PdfPages(self.outfile) as pdf:
            for param, tex in zip(self.labels, self.texlabels):
                flatchain = self.chains[param].values
                wchain = flatchain.reshape((self.nwalkers, -1))

                _ = pl.figure(figsize=(18, 10))
                for w in range(self.nwalkers):
                    pl.plot(
                        wchain[w, :], '.', rasterized=True, color=self.colors[w],
                        markersize=3
                    )
```
perhaps in:
```
wchain = flatchain.reshape((self.nwalkers, -1))
```

**Comment by bjfultn** [comment]
Very interesting, this could also be an issue with the random number generation not actually being independent between ensembles.

**Comment by spencer3616** [comment]
There ended up being two problems shown in the trend plot. First off, there was a chain reshaping error. Additionally, each walker was returning to its original position after a certain number of steps passed. Both of these problems will be fixed after the release of some recent changes.
