### ISSUE TITLE
Time format problem?

### ISSUE THREAD

**Issue by aberrico** [California-Planet-Search/radvel#283]
I define and initialize my model as follows:

def initialize_model():
    time_base = 2452130
    params = radvel.Parameters(1,basis='per tc secosw sesinw logk')
    params['per1'] = radvel.Parameter(value=3.971)
    params['tc1'] = radvel.Parameter(value=2452130)
    params['secosw1'] = radvel.Parameter(value=0)
    params['sesinw1'] = radvel.Parameter(value=0)
    params['logk1'] = radvel.Parameter(value=3.7)
    mod = radvel.RVModel(params, time_base=time_base)
    return mod
	
mod = initialize_model()
like = radvel.likelihood.RVLikelihood(mod, t, vel, errvel)
print (like)

parameter                     value      vary
per1                          3.971       True
tc1                            2130       True
secosw1                           0       True
sesinw1                           0       True
logk1                           3.7       True
dvdt                              0       True
curv                              0       True
gamma                           nan       True
jit                             nan       True

After the likelihood command, tc seems to loose the first 3 digits. Note that in the definition it was 2452130 and when printing like it is 2130.

Is this a formatting problem?

**Comment by bjfultn** [comment]
The `__repr__` function of the likelihood object was simply subtracting 2450000 for display purposes. I just changed it to subtract whatever the user enters for `model.time_base` instead. This will be released in v1.3.2. 

For now, this is just a bug with the print/display so you should be able to continue without worry.
