### ISSUE TITLE
PERF: low eccentricity orbits

### ISSUE THREAD

**Issue by petigura** [California-Planet-Search/radvel#31]
@bjfultn,

I think there might be a way to optimize solving Kepler's equation in the (often used) low eccentricity case. The current solver uses Danby's method, which requires several iterations and requires 2 + 3N trig evals where N is the number of iterations.

http://www.projectpluto.com/kepler.htm

``` C
if( ecc < .3)     /* low-eccentricity formula from Meeus,  p. 195 */
   {
   curr = atan2( sin( mean_anom), cos( mean_anom) - ecc);
         /* one correction step,  and we're done */
   err = curr - ecc * sin( curr) - mean_anom;
   curr -= err / (1. - ecc * cos( curr));
   return( curr);
   }
```

requires 5 trig evals and is done.

Of course, we'll only see any appreciable speed up if Kepler's equation is the dominant CPU burden. Converting between the dictionary basis and the array basis every iteration might also have some significant overhead.

**Comment by bjfultn** [comment]
I added a check in `kepler.rv_drive` yesterday for e == 0:
```
if e == 0.0:
        return k * np.cos( (t-tp) / per)
```
The improvements were fairly small. I went from ~3600 steps/s without this to ~4200 steps/s in the MCMC chains for a two-planet circular fit of HD 3167. However, `kepler.profile` reports a ~3.7x speedup with this new check. This suggests that `kepler.rv_drive` is not the limiting step at this point.

**Comment by awhoward** [comment]
BJ, in your equation, I think mean "(t-tc) / per" instead of "(t-tp) / per".  Although tp isn't formally defined for e=0, you can still convert from {tp,om} to tc for e=0.

**Comment by bjfultn** [comment]
Following along with the e > 0 implementation:
```
        M = 2 * np.pi * ( ((t - tp) / per) - np.floor( (t - tp) / per ) )
        eccarr = np.zeros(t.size) + e
        E1 = kepler(M, eccarr)
        # Calculate nu
        nu = 2 * np.arctan( ( (1+e) / (1-e) )**0.5 * np.tan( E1 / 2 ) )
        # Calculate the radial velocity
        rv = k * ( np.cos( nu + om ) + e * np.cos( om ) ) 
```

 I believe that this is the correct form for the e=0 case:
```
    if e == 0.0:
        M = 2 * np.pi * ( ((t - tp) / per) - np.floor( (t - tp) / per ) )
        return k * np.cos( M + om)
```

**Comment by petigura** [comment]
@bjfultn: my guess is that there is some overhead that's required in resolving the string names of the parameters and converting them to the fitting basis using the python objects there is probably a way to retain the clean API, while reducing the number of times that python objects are created/modified. Before proceeding let's do some careful line-by-line profiling.

**Comment by bjfultn** [comment]
I think that we can close this. The above comment is handled in issue #48.
