### ISSUE TITLE
Gaussian Process Fitting - different Ks on plots?

### ISSUE THREAD

**Issue by andreeaih** [California-Planet-Search/radvel#320]
Hi, I am using the Gaussian Process feature from radvel and I was curious why is it that the semi-amplitude is different in GPPlot.plot_multipanel from the one from the Corner plot. This happens in the tutorial that you have posted (https://github.com/California-Planet-Search/radvel/blob/master/docs/tutorials/GaussianProcess-tutorial.ipynb). 
I ran radvel on my computer with GPs on a different dataset and I get a 1m/s difference between the two plots. I am guessing gp posterior - "gppost"- is not updated after the gp analysis was performed. Maybe there is something that I do not understand and this is how is supposed to be but I figured I could ask.
Radvel version 1.4.1.

**Comment by bjfultn** [comment]
I believe `plot_multipanel` shows the maximum a posteriori value, but the corner plot shows the median value from the posterior. Check the table of parameters in the PDF report (which shows both) to verify that is the case.

**Comment by andreeaih** [comment]
Yes, you are right. Thank you for the help.
