### ISSUE TITLE
Plotting error when planet not found

### ISSUE THREAD

**Issue by arpita308** [California-Planet-Search/radvel#323]
I was getting a value error from GridSpec when the data had no planets, saying that ncols could not be 0. Fix that I used:

plot_multipanel in orbit_plots.py 
Line 454            gs_phase = gridspec.GridSpec(self.phase_nrows, self.phase_ncols)
change to
Line 454            gs_phase = gridspec.GridSpec(max([1,self.phase_nrows]), max([1,self.phase_ncols]))

**Comment by bjfultn** [comment]
Thanks! I added this patch in PR #388 and this will be released in v1.4.2
