### ISSUE TITLE
minAfactor documentation

### ISSUE THREAD

**Issue by zhexingli** [California-Planet-Search/radvel#332]
I believe for mcmc to converge, minAfactor of the chain has to go above the default value of 40 (as indicated by the summary pdf as well), because autocorrelation time will plateau when the number of steps is large, giving N/tau a larger number. But in the documentation page, it says "once the minimum autocorreclation factor is below minAfactor, this criterion for convergence is met." This seems confusing.

**Comment by bjfultn** [comment]
I believe this is just a typo, "below" --> "above". @spencerhurt do you agree?

**Comment by spencerhurt** [comment]
You're right, this is just a typo. Submitted a pull request to the next-release branch.
