### ISSUE TITLE
gamma and jitter with vary=False, linear=True

### ISSUE THREAD

**Issue by tronsgaard** [California-Planet-Search/radvel#339]
Hi radvel team!

I think I understand how to use Tim Brandt's trick to set `vary=False, linear=True` and construct the gamma posterior from the remaining free parameters. Reading the note [here](http://cadence.caltech.edu/~bfulton/share/Marginalizing_the_likelihood.pdf), it also seems possible to do it for the jitter parameter instead. 
However, in the GaussianProcess tutorial notebook, both the gamma and jitter parameters are defined with `vary=False, linear=True`. It is not obvious (at least not to me) how to derive posteriors for both gamma and jitter at the same time? The problem seems underdetermined - has anyone tried it, or is this by any chance a mistake in the Gaussian Process tutorial?

Thanks,
René

**Comment by bjfultn** [comment]
This is an error. The linearization trick is only implemented for the gamma terms. Will be fixed in the next release.
