### ISSUE TITLE
Using a list in EccentricityPrior raises TypeError

### ISSUE THREAD

**Issue by vandalt** [California-Planet-Search/radvel#347]
Hi,
When using a list to initialize `EccentricityPrior`, I get the following error:
```python
----> 1 radvel.prior.EccentricityPrior([1, 2])

~/astro/radvel/radvel/prior.py in __init__(self, num_planets, upperlims)
     96
     97         if type(upperlims) == float:
---> 98             self.upperlims = [upperlims] * npl
     99         else:
    100             assert len(upperlims) == len(self.planet_list), "Number of eccentricity \

TypeError: can't multiply sequence by non-int of type 'list'
```
This seems to happen because `npl` is set to `num_planet` when it is a list (see [Line 95](https://github.com/California-Planet-Search/radvel/blob/master/radvel/prior.py#L95)). I just checked and changing `npl` to always be `len(self.planet_list)` or switching lines 92 and 95 both work.

**Comment by bjfultn** [comment]
The calling syntax should be `radvel.prior.EccentricityPrior(2, 0.90)` (for example). This would put a hard upper limit at e=0.9 for all (2) planets in the system.

**Comment by vandalt** [comment]
Using an integer indeed works, but [the documentation](https://radvel.readthedocs.io/en/latest/prior.html#radvel.prior.EccentricityPrior) specifies that `num_planets` can be either an integer or a list. And the code currently handles both cases, but does not assign `npl` to an integer or a list. The integer option works fine for my current use-case, but the list option could be useful when one planet has a fixed circular orbit or has a different eccentricity prior for some reason. I'd be happy to send a PR with this modification (it's only a two-line modification), but I understand if you prefer to support only the integer syntax in the future.

**Comment by vandalt** [comment]
> If you want to fix eccentricity you should use the `vary=False` keyword on the `Parameters` objects that you want to fix.

Yeah sorry that wasn't clear, I meant that once it is set to `vary=False`, not setting a prior on it makes sense from the perspective of a user. It was just an example of a use-case where the list option is useful.

> So the fix here would be to make upperlims a list with the same length as num_planets if num_planets is provided as a list and upperlims is not.

This was already implemented, the only issue was that instead of using the length of `num_planets` to make an `upperlims` list, `num_planets` itself was used (hence the `TypeError`).

See #348 for the PR!

**Comment by bjfultn** [comment]
Great, lets continue the discussion on the PR thread.
