### ISSUE TITLE
DeprecationWarning: `np.int`

### ISSUE THREAD

**Issue by Yacheng-Kang** [California-Planet-Search/radvel#351]
When I use the RadVel, I always get the following deprecation warning:

/opt/anaconda3/lib/python3.8/site-packages/autograd/numpy/numpy_wrapper.py:20: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int_types = {_np.int, _np.int8, _np.int16, _np.int32, _np.int64, _np.integer}

How can I solve this?

**Comment by bjfultn** [comment]
You can safely ignore this warning and everything should still function as expected. I'll take care of this in the next version release.
