### ISSUE TITLE
`phase_ncols` and `phase_nrows` are not set as attribute when passed as arguments

### ISSUE THREAD

**Issue by vandalt** [California-Planet-Search/radvel#357]
Hi,
In the `MultipanelPlot` class, when `phase_ncols` or `phase_nrows` are passed as keyword argument, it seems that they are never set as attribute. I think an `else` for each of them would fix this.

https://github.com/California-Planet-Search/radvel/blob/a39924064a052ffc84703872225eee3f89447176/radvel/plot/orbit_plots.py#L74-L77

I'm happy to send a PR with this, but I preferred to open an issue first. Since the fix is simple, I thought you might prefer to add it directly.

**Comment by bjfultn** [comment]
Go ahead and submit a PR if you are there working in the code.

**Comment by bjfultn** [comment]
Fixed in PR #362 and will be released with 1.4.10
