### ISSUE TITLE
RadVel Pip Install Fail due to Inability to Build Wheel

### ISSUE THREAD

**Issue by ngierty** [California-Planet-Search/radvel#375]
Hello,

I recently had to install a clean version of Anaconda due to a separate setup issue and as part of this I installed Radvel. When I initially installed Radvel, I got a message saying "pip install failed due to inability to build wheel". Adding pip to the conda environment (conda install -n myenv pip), let me install Radvel but with the attached Deprecation Error. (I still had to install Celerite and h5py separately.)

I figured I would post it here for anybody else with this issue.

<img width="1726" alt="error" src="https://user-images.githubusercontent.com/35086628/235753449-250db0d9-3c9f-44ab-9474-393b5ebb6ef7.png">

**Comment by nespinoza** [comment]
Hey @ngierty --- it is kind of hidden, but this is due to a C-python error. If you do `pip install cython` this goes away.

**Comment by ngierty** [comment]
Thank you!
