### ISSUE TITLE
nbsphinx import causes radvel to fail to import

### ISSUE THREAD

**Issue by semaphoreP** [California-Planet-Search/radvel#376]
I'm running radvel on Google Colab on Python 3.10, and the `import nbsphinx` command causes the radvel import to crash. I don't understand why yet. 

<img width="524" alt="image" src="https://github.com/California-Planet-Search/radvel/assets/2245740/4e7e6a93-b9c8-4f7d-a796-29d25011b915">

**Comment by bjfultn** [comment]
looks like something to do with the sphinx version? Did you ever figure it out?

**Comment by semaphoreP** [comment]
Not at the time, but I just tested it in a fresh Colab, and it's working fine now. I'm guessing Google updated their python setup for Colab, so it's a non-issue now. Closing this issue.
