### ISSUE TITLE
should remove / try except clause

### ISSUE THREAD

**Issue by petigura** [California-Planet-Search/radvel#38]
Use of try/except is generally not a good idea because it's not clear what mode the code is operating in. In this code block, it seems like `tp` should not be defined and that the try block should never proceed.

```
if newbasis == 'per tc e w k':               per = _getpar('per')
               e = _getpar('e')
               w = _getpar('w')
               k = _getpar('k')
               try:
                   tp = _getpar('tp')
               except KeyError:
                   tp = timetrans_to_timeperi(_getpar('tc'), per, e, w)
                   _setpar('tp', tp)
```

**Comment by petigura** [comment]
As we discussed we should be explicit about what basis we're in, i.e. tc and tp should never appear in the same dictionary or pandas dataframe

**Comment by bjfultn** [comment]
Removed all try/except clauses from `basis.py`. See commit 393f9e0
