### ISSUE TITLE
degree_radian_bug_in_from_cps

### ISSUE THREAD

**Issue by sealauren** [California-Planet-Search/radvel#46]
In to_cps, w is converted to degrees at the end:
            # shoves cps parameters from namespace into param_out
            _setpar('per', per)
            _setpar('tp', tp)
            _setpar('e', e)
            _setpar('w', np.degrees(w))
            _setpar('k', k)

In from_cps, w is never converted from (degrees?) to radians.  Here is an example using the 'per tc secosw sesinw k' basis, with my comment in allcaps near the potentially buggy lines.  This bug might be in other basis conversions as well.

            if newbasis == 'per tc secosw sesinw k':
                per = _getpar('per')
                e = _getpar('e')
                w = _getpar('w')
                k = _getpar('k')
                try:
                    tp = _getpar('tp')
                except KeyError:
                    tp = timetrans_to_timeperi(_getpar('tc'), per, e, w)
                    _setpar('tp', tp)
                    
                _setpar('secosw', np.sqrt(e)*np.cos(w) )  # W IN DEGREES OR RADIANS?
                _setpar('sesinw', np.sqrt(e)*np.sin(w) ) # W IN DEGREES OR RADIANS?
                _setpar('k', k )
                _setpar('tc', timeperi_to_timetrans(tp, per, e, w) )

                if not kwargs.get('keep', True):
                    _delpar('tp')
                    _delpar('e')
                    _delpar('w')

                self.name = newbasis
                self.params = newbasis.split()

        return params_out

**Comment by bjfultn** [comment]
I believe that this is fixed now. Omega is always in radians and never converted to degrees now. See issue #41

**Comment by petigura** [comment]
but to confirm, the code was handling the conversion from deg to rad correctly before. This was an internal refactoring, right?

**Comment by bjfultn** [comment]
There were problems if you were using the 'per tp e w k' (cps) or the 'per tc e w k' fitting basis, but otherwise any previous RadVel fits are OK.
