### ISSUE TITLE
Median vs best fit parameters

### ISSUE THREAD

**Issue by iancrossfield** [California-Planet-Search/radvel#52]
When Radvel is run in "fit" and "mcmc" modes, the parameters reported in the final tables are the median of the distribution rather than the best-fit values. Sometimes the one set is substantially different than the other -- it would be nice to warn the user when this happens.

**Comment by bjfultn** [comment]
Now I report both the credible intervals and the maximum likelihood parameter values in the LaTeX table. See pull request #59
