### ISSUE TITLE
Hangs while creating report

### ISSUE THREAD

**Issue by iancrossfield** [California-Planet-Search/radvel#55]
On some systems, when generating a report with kepfit.py the code will hang indefinitely after generating the multipanel_rv plot.

**Comment by iancrossfield** [comment]
This problem occurs when calling pdflatex, and pdflatex encounters an error. The command-line pdflatex waits for user input, but the user never sees it because it's hidden inside the subprocess.Popen call.  

In my case, the problem was that pdflatex was installed but a number of key tex class and style files (emulateapj.cls, a number of RevTex files, etc.) were not in the proper path.  I put a bunch of these in the bowels of /usr/share/texlive/texmf-dist/, and everything now works.

**Comment by petigura** [comment]
Sounds like this is resolved, closing.
