### ISSUE TITLE
Adjusting MCMC for multi-planet system

### ISSUE THREAD

**Issue by ruben-santana** [California-Planet-Search/radvel#67]
I started using Radvel for a couple months now and I have basic coding experience, but I had a lot of trouble trying to run mcmc on the command prompt for a 4 or greater planet system. I later found that reducing the default nwalkers or nsteps helped with this problem.

I recommend adding at little note on the "Getting Started" page located in 'radvel/docs/quickstartcli.rst' that mentions how to deal with larger number of planets, and possibly giving examples on how to use these added arguments.

ex. $ radvel mcmc -s /path/to/HD164922.py  --nwalkers=100

**Comment by bjfultn** [comment]
I've added a check that the number of walkers is at least 2 times the number of free parameters. The number of walkers will automatically be adjusted if necessary. This fix will be available in the next release. For now you may manually specify a number of walkers using the `--nwalkers` flag as you do in the example. Or you may checkout and install the `next-release` branch.
