### ISSUE TITLE
Continuous Integration with Travis

### ISSUE THREAD

**Issue by petigura** [California-Planet-Search/radvel#77]
Given that we want to try to support python 2 and 3 at least for the time being. I think it's important to test compliance in an automated way. We can cover both python 2 and 3 with travis.

https://travis-ci.org/
https://docs.travis-ci.com/user/languages/python/
https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo

Here's a simple example from DFM's corner package.

https://github.com/dfm/corner.py/blob/master/.travis.yml

**Comment by sblunt** [comment]
Done!
