### ISSUE TITLE
Fix MCMC multi-threading

### ISSUE THREAD

**Issue by bjfultn** [California-Planet-Search/radvel#8]
MCMC is buggy when we use it's used in a multi-threaded way. Is this becase we're creating multiple instances of the posterior object and it's not being passed around properly?

**Comment by bjfultn** [comment]
The initial problem was resolved by switching to an `OrderedDict` implementation of the `Parameters` object. I'm keeping this open to address the new issues multithreading w/ GPs.

**Comment by bjfultn** [comment]
Assigning to @sblunt since she has been working on this issue lately.

**Comment by sblunt** [comment]
MCMC `multiprocessing` with GPs should be working properly now. Informative warnings are given to users trying to run `multiprocessing` on an `Accelerate`-based `numpy` installation, and detailed documentation is available [here](http://radvel.readthedocs.io/en/latest/OSX-multiprocessing.html#osx-multiprocessing). @bjfultn I think we can close this issue unless you know of some other problems.
