### ISSUE TITLE
Example not working in Version2

### ISSUE THREAD

**Issue by bjfultn** [California-Planet-Search/radvel#85]
Oops, I merged too soon. The HD164922_sarahtest example is not working in the `version2` branch. The `version2` branch should be a working version that agrees with the `version2` docs: http://radvel.readthedocs.io/en/version2/. Lets get this branch working again, or we can revert back to a working commit if needed.

**Comment by sblunt** [comment]
That's my fault-- I didn't mean to request that the `sarah` branch be merged with the `version2` branch. I suggest reverting to the previous commit (without any of my changes), then once I have the RVParameters -> Parameters change implemented and tested, we can merge `sarah` with `version2`.

**Comment by bjfultn** [comment]
OK no worries. I think I got it up and running again.

**Comment by sblunt** [comment]
Thanks! Sorry about that.
